import PDFDocument from 'pdfkit';
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '../lib/supabaseServer.js';
import { Sentry } from '../lib/sentry-server.js';

export const config = { maxDuration: 60 };

// ── Design tokens ─────────────────────────────────────────────────────────────
const GRAPHITE = '#222222';
const GOLD     = '#B89030';
const TEXT     = '#333333';
const MUTED    = '#888888';
const LIGHT    = '#F5F5F0';
const MID_BG   = '#EBEBE6';
const TOTAL_BG = '#FFF8E8';

// Page geometry (Letter, pts)
const PW = 612, PH = 792;
const ML = 40, MR = 40;
const CW = PW - ML - MR;   // 532
const CT = 56;              // content top (below header bar)
const CB = 756;             // content bottom (above footer)

// ── Format helpers ────────────────────────────────────────────────────────────
const $c  = n => '$' + Math.round(n || 0).toLocaleString('en-US');
const $sf = n => '$' + ((n || 0)).toFixed(2);
const pct = n => ((n || 0) * 100).toFixed(1) + '%';
const short = (s, max = 40) => s && s.length > max ? s.slice(0, max - 1) + '…' : (s || '');

// ── Cost calculation (mirrors src/engine/CostEngine.js) ───────────────────────
const N = v => { const n = Number(v); return isNaN(n) ? 0 : n; };

function itemMid(it)  { return (N(it.qty_min) + N(it.qty_max)) / 2 * N(it.unit_cost_mid); }
function itemLow(it)  { return N(it.qty_min) * N(it.unit_cost_low); }
function itemHigh(it) { return N(it.qty_max) * N(it.unit_cost_high); }

function applyMarkups(base, g) {
  const co  = base * N(g.contingency);
  const gc  = (base + co) * N(g.generalConditions);
  const fe  = (base + co + gc) * N(g.fee);
  const insRate = N(g.insurance) + N(g.bond);
  const ins = (base + co + gc + fe) * insRate;
  const tx  = base * 0.45 * N(g.tax);
  return { base, co, gc, fe, ins, tx, tot: base + co + gc + fe + ins + tx };
}

function computeTotals(items, globals) {
  let lR = 0, mR = 0, hR = 0;
  items.forEach(it => {
    lR += itemLow(it);
    mR += itemMid(it);
    hR += itemHigh(it);
  });
  const factor = (1 + N(globals.escalation)) * N(globals.regionFactor || 1);
  return {
    rawMid: mR, rawLow: lR, rawHigh: hR,
    factor,
    full: {
      l: applyMarkups(lR * factor, globals),
      m: applyMarkups(mR * factor, globals),
      h: applyMarkups(hR * factor, globals),
    },
  };
}

// ── PDF primitive helpers ─────────────────────────────────────────────────────
let _pageNum = 0;

function addPage(doc) {
  doc.addPage({ size: 'LETTER', margins: { top: 0, left: 0, right: 0, bottom: 0 } });
  _pageNum++;
  drawPageChrome(doc);
  return CT;
}

function drawPageChrome(doc) {
  // Header bar
  doc.rect(0, 0, PW, 44).fill(GRAPHITE);
  doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(14)
     .text('COSTDECK', ML, 15, { lineBreak: false });
  // Footer
  doc.rect(0, PH - 30, PW, 30).fill('#F9F9F8');
  doc.rect(0, PH - 31, PW, 1).fill('#DDDDDD');
  doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
     .text('Generated by CostDeck — costdeck.ai', ML, PH - 20, { lineBreak: false });
  doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
     .text(`Page ${_pageNum}`, PW - MR - 40, PH - 20, { width: 40, align: 'right', lineBreak: false });
}

function sectionTitle(doc, y, title) {
  doc.rect(ML, y, CW, 22).fill(GRAPHITE);
  doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(9)
     .text(title.toUpperCase(), ML + 8, y + 7, { lineBreak: false });
  return y + 30;
}

function label(doc, y, lbl, val, labelW = 150) {
  doc.fillColor(MUTED).font('Helvetica').fontSize(8.5)
     .text(lbl, ML, y, { width: labelW, lineBreak: false });
  doc.fillColor(TEXT).font('Helvetica').fontSize(8.5)
     .text(val || '—', ML + labelW, y, { lineBreak: false });
  return y + 14;
}

// ── Generic table renderer ────────────────────────────────────────────────────
// columns: [{key, label, width, align}]
// rows:    [{...data, _type?: 'category'|'subtotal'|'total'}]
// Returns new y.
function drawTable(doc, x, startY, columns, rows, opts = {}) {
  const ROW_H  = opts.rowH || 17;
  const HDR_H  = opts.hdrH || 20;
  const PAD    = opts.pad  || 5;
  const FS     = opts.fs   || 7.5;
  const totalW = columns.reduce((s, c) => s + c.width, 0);

  function drawHeader(y) {
    doc.rect(x, y, totalW, HDR_H).fill(GRAPHITE);
    let cx = x;
    for (const col of columns) {
      doc.fillColor('white').font('Helvetica-Bold').fontSize(FS - 0.5)
         .text(col.label, cx + PAD, y + (HDR_H - FS + 1) / 2,
               { width: col.width - PAD * 2, align: col.align || 'left', lineBreak: false });
      cx += col.width;
    }
    return y + HDR_H;
  }

  function drawRow(y, row, isOdd) {
    const isCategory = row._type === 'category';
    const isSubtotal = row._type === 'subtotal';
    const isTotal    = row._type === 'total';
    const isSpacer   = row._type === 'spacer';

    if (isSpacer) { return y + 6; }

    const bg   = isCategory ? '#3A3A3A'
               : isTotal    ? TOTAL_BG
               : isSubtotal ? MID_BG
               : isOdd      ? LIGHT
               : 'white';
    const fg   = isCategory ? 'white'
               : isTotal    ? GOLD
               : TEXT;
    const font = (isCategory || isSubtotal || isTotal) ? 'Helvetica-Bold' : 'Helvetica';
    const rh   = isCategory ? ROW_H + 1 : ROW_H;

    doc.rect(x, y, totalW, rh).fill(bg);
    let cx = x;
    for (const col of columns) {
      const val = row[col.key] ?? '';
      doc.fillColor(fg).font(font).fontSize(FS)
         .text(String(val), cx + PAD, y + (rh - FS) / 2 - 0.5,
               { width: col.width - PAD * 2, align: col.align || 'left', lineBreak: false });
      cx += col.width;
    }
    return y + rh;
  }

  let y = drawHeader(startY);
  let oddRow = 0;

  for (const row of rows) {
    const rh = row._type === 'category' ? ROW_H + 1
             : row._type === 'spacer'   ? 6
             : ROW_H;

    if (y + rh > CB) {
      y = addPage(doc);
      y = drawHeader(y);
    }

    y = drawRow(y, row, oddRow % 2 === 1);
    if (!row._type || row._type === 'subtotal') oddRow++;
  }

  return y;
}

// ── Page builders ─────────────────────────────────────────────────────────────

function buildCoverPage(doc, project) {
  const cx = PW / 2;

  // Full graphite top band
  doc.rect(0, 0, PW, 180).fill(GRAPHITE);

  // Logo mark (crosshair)
  const lx = cx, ly = 110, r = 34;
  doc.circle(lx, ly, r).lineWidth(1.5).strokeColor(GOLD).stroke();
  doc.circle(lx, ly, r * 0.3).lineWidth(1).strokeColor(GOLD).stroke();
  doc.moveTo(lx - r * 1.35, ly).lineTo(lx - r * 1.05, ly).lineWidth(0.75).strokeColor(GOLD).stroke();
  doc.moveTo(lx + r * 1.05, ly).lineTo(lx + r * 1.35, ly).stroke();
  doc.moveTo(lx, ly - r * 1.35).lineTo(lx, ly - r * 1.05).stroke();
  doc.moveTo(lx, ly + r * 1.05).lineTo(lx, ly + r * 1.35).stroke();

  doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(18)
     .text('COSTDECK', 0, 148, { width: PW, align: 'center', lineBreak: false });

  // Project name
  doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(26)
     .text(project.name || 'Untitled Project', ML, 210,
           { width: CW, align: 'center', lineBreak: false });

  doc.fillColor(MUTED).font('Helvetica').fontSize(13)
     .text('Construction Cost Estimate', ML, 244, { width: CW, align: 'center', lineBreak: false });

  // Gold rule
  doc.rect(ML, 270, CW, 1).fill(GOLD);

  // Detail box
  const bx = ML + 60, bw = CW - 120;
  doc.rect(bx, 284, bw, 160).fill('#F9F9F8').rect(bx, 284, bw, 160).strokeColor('#E0E0DA').lineWidth(0.5).stroke();

  const details = [
    ['Location',        `${project.city || ''}${project.city && project.state ? ', ' : ''}${project.state || ''}`.trim() || '—'],
    ['Building Type',   project.building_type || '—'],
    ['Delivery Method', project.delivery_method || '—'],
    ['Date Generated',  new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })],
  ];

  let dy = 302;
  for (const [lbl, val] of details) {
    doc.fillColor(MUTED).font('Helvetica').fontSize(9)
       .text(lbl, bx + 16, dy, { width: 120, lineBreak: false });
    doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(9)
       .text(val, bx + 140, dy, { lineBreak: false });
    dy += 26;
  }

  // Footer tagline
  doc.rect(0, PH - 60, PW, 60).fill(GRAPHITE);
  doc.fillColor(MUTED).font('Helvetica').fontSize(9)
     .text('Prepared by CostDeck — costdeck.ai', 0, PH - 36, { width: PW, align: 'center', lineBreak: false });
}

function buildExecutiveSummary(doc, project, totals, globals) {
  let y = sectionTitle(doc, CT, 'Executive Summary');
  y += 8;

  const bsf = N(globals.buildingSF) || 1;
  const lvls = [
    { label: 'LOW ESTIMATE',  color: '#4A7C59', total: totals.full.l.tot },
    { label: 'MID ESTIMATE',  color: GOLD,      total: totals.full.m.tot },
    { label: 'HIGH ESTIMATE', color: '#8B4513', total: totals.full.h.tot },
  ];

  const boxW = 168, boxH = 80, gap = 14;
  let bx = ML;
  for (const lv of lvls) {
    doc.rect(bx, y, boxW, boxH).fill('#F9F9F8')
       .rect(bx, y, boxW, 5).fill(lv.color);
    doc.fillColor(lv.color).font('Helvetica-Bold').fontSize(7.5)
       .text(lv.label, bx + 10, y + 14, { lineBreak: false });
    doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(18)
       .text($c(lv.total), bx + 10, y + 26, { lineBreak: false });
    doc.fillColor(MUTED).font('Helvetica').fontSize(9)
       .text($sf(lv.total / bsf) + '/SF', bx + 10, y + 50, { lineBreak: false });
    bx += boxW + gap;
  }
  y += boxH + 20;

  // Project metrics
  doc.rect(ML, y, CW, 1).fill('#E0E0DA');
  y += 10;
  const col2 = ML + CW / 2;
  const metrics = [
    ['Total Building Area',  `${N(globals.buildingSF).toLocaleString()} SF`],
    ['Parking Stalls',       N(globals.parkingStalls) > 0 ? N(globals.parkingStalls).toString() : '—'],
    ['Delivery Method',      project.delivery_method || '—'],
    ['Labor Type',           project.labor_type || '—'],
    ['Region Factor',        pct(N(globals.regionFactor) - 1 >= 0 ? N(globals.regionFactor) - 1 : 0) + ' adj. (×' + (N(globals.regionFactor || 1)).toFixed(2) + ')'],
    ['Escalation Rate',      pct(N(globals.escalation))],
  ];

  for (let i = 0; i < metrics.length; i += 2) {
    const x1 = ML, x2 = col2;
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(metrics[i][0], x1, y, { width: 130, lineBreak: false });
    doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(8).text(metrics[i][1], x1 + 130, y, { lineBreak: false });
    if (metrics[i + 1]) {
      doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(metrics[i + 1][0], x2, y, { width: 130, lineBreak: false });
      doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(8).text(metrics[i + 1][1], x2 + 130, y, { lineBreak: false });
    }
    y += 16;
  }

  y += 10;
  doc.rect(ML, y, CW, 1).fill('#E0E0DA');
  y += 12;
  doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
     .text(
       'Cost estimate based on preliminary program information. Actual costs may vary based on final design, ' +
       'market conditions, and site-specific factors. All amounts in USD.',
       ML, y, { width: CW, lineBreak: true }
     );
}

function buildCategorySummary(doc, items, totals, globals) {
  let y = sectionTitle(doc, CT, 'Cost Summary by Category');
  y += 4;

  const bsf = N(globals.buildingSF) || 1;
  const grandMid = totals.full.m.tot;

  // Compute per-category raw totals
  const catMap = {};
  for (const it of items) {
    if (!catMap[it.category]) catMap[it.category] = { l: 0, m: 0, h: 0 };
    catMap[it.category].l += itemLow(it);
    catMap[it.category].m += itemMid(it);
    catMap[it.category].h += itemHigh(it);
  }

  const factor = totals.factor;
  const cols = [
    { key: 'cat',  label: 'Category',      width: 165, align: 'left' },
    { key: 'low',  label: 'Low Total',      width: 80,  align: 'right' },
    { key: 'mid',  label: 'Mid Total',      width: 80,  align: 'right' },
    { key: 'high', label: 'High Total',     width: 80,  align: 'right' },
    { key: 'psf',  label: '$/SF (Mid)',     width: 62,  align: 'right' },
    { key: 'pct',  label: '% of Total',     width: 65,  align: 'right' },
  ];

  const rows = Object.entries(catMap).map(([cat, t]) => {
    const scaledMid = t.m * factor;
    const fullMid   = applyMarkups(scaledMid, globals).tot;
    return {
      cat,
      low:  $c(applyMarkups(t.l * factor, globals).tot),
      mid:  $c(fullMid),
      high: $c(applyMarkups(t.h * factor, globals).tot),
      psf:  $sf(fullMid / bsf),
      pct:  grandMid > 0 ? ((fullMid / grandMid) * 100).toFixed(1) + '%' : '—',
    };
  });

  rows.push({ _type: 'total',
    cat: 'TOTAL PROJECT COST',
    low:  $c(totals.full.l.tot),
    mid:  $c(totals.full.m.tot),
    high: $c(totals.full.h.tot),
    psf:  $sf(totals.full.m.tot / bsf),
    pct:  '100.0%',
  });

  y = drawTable(doc, ML, y, cols, rows);
}

function buildMarkupsBreakdown(doc, totals, globals) {
  let y = sectionTitle(doc, CT, 'Cost Buildup & Markups');
  y += 4;

  const m   = totals.full.m;
  const bsf = N(globals.buildingSF) || 1;
  const insRate = N(globals.insurance) + N(globals.bond);
  const insBase = m.base + m.co + m.gc + m.fe;
  const insAmt  = insRate > 0 ? m.ins * N(globals.insurance) / insRate : 0;
  const bondAmt = insRate > 0 ? m.ins * N(globals.bond)      / insRate : 0;

  const cols = [
    { key: 'desc', label: 'Cost Component',     width: 260, align: 'left' },
    { key: 'rate', label: 'Rate',                width: 82,  align: 'right' },
    { key: 'amt',  label: 'Amount (Mid)',         width: 190, align: 'right' },
  ];

  const rawMid     = totals.rawMid;
  const regionAdj  = rawMid * (N(globals.regionFactor || 1) - 1);
  const escAdj     = rawMid * N(globals.regionFactor || 1) * N(globals.escalation);
  const adjustedDC = rawMid * totals.factor;

  const rows = [
    { desc: 'Raw Construction Cost (sum of line items)',  rate: '—',                           amt: $c(rawMid) },
    { desc: `Regional Cost Factor`,                       rate: '×' + (N(globals.regionFactor||1)).toFixed(2), amt: $c(regionAdj) },
    { desc: `Escalation`,                                 rate: pct(N(globals.escalation)),   amt: $c(escAdj) },
    { _type: 'subtotal', desc: 'ADJUSTED DIRECT COST',   rate: '',                             amt: $c(adjustedDC) },
    { _type: 'spacer' },
    { desc: 'Contingency',                                rate: pct(N(globals.contingency)),   amt: $c(m.co) },
    { desc: 'General Conditions',                         rate: pct(N(globals.generalConditions)), amt: $c(m.gc) },
    { desc: 'GC Fee / Overhead',                          rate: pct(N(globals.fee)),           amt: $c(m.fe) },
    { desc: 'Insurance',                                  rate: pct(N(globals.insurance)),     amt: $c(insAmt) },
    { desc: 'Performance & Payment Bond',                 rate: pct(N(globals.bond)),          amt: $c(bondAmt) },
    { desc: 'Sales Tax (on ~45% materials)',              rate: pct(N(globals.tax)),           amt: $c(m.tx) },
    { _type: 'spacer' },
    { _type: 'total', desc: 'TOTAL ESTIMATED COST (MID)', rate: '', amt: $c(m.tot) },
    { _type: 'subtotal', desc: `Cost per SF (${N(globals.buildingSF).toLocaleString()} SF)`, rate: '', amt: $sf(m.tot / bsf) },
  ];

  y = drawTable(doc, ML, y, cols, rows);
}

function buildTopTen(doc, items, totals, globals) {
  let y = sectionTitle(doc, CT, 'Top 10 Cost Drivers');
  y += 4;

  const factor   = totals.factor;
  const grandMid = totals.full.m.tot;

  const sorted = [...items]
    .map(it => ({ ...it, _mid: applyMarkups(itemMid(it) * factor, globals).tot }))
    .filter(it => it._mid > 0)
    .sort((a, b) => b._mid - a._mid)
    .slice(0, 10);

  const cols = [
    { key: 'rank', label: '#',            width: 24,  align: 'center' },
    { key: 'desc', label: 'Description',  width: 225, align: 'left' },
    { key: 'cat',  label: 'Category',     width: 133, align: 'left' },
    { key: 'amt',  label: 'Total (Mid)',  width: 100, align: 'right' },
    { key: 'pct',  label: '% Total',      width: 50,  align: 'right' },
  ];

  const rows = sorted.map((it, i) => ({
    rank: i + 1,
    desc: short(it.description || it.subcategory || '—', 38),
    cat:  short(it.category, 22),
    amt:  $c(it._mid),
    pct:  grandMid > 0 ? ((it._mid / grandMid) * 100).toFixed(1) + '%' : '—',
  }));

  y = drawTable(doc, ML, y, cols, rows);
}

function buildDetailedLineItems(doc, items, globals) {
  let y = sectionTitle(doc, CT, 'Detailed Cost Estimate');
  y += 4;

  const factor = (1 + N(globals.escalation)) * N(globals.regionFactor || 1);

  const cols = [
    { key: 'desc', label: 'Description',        width: 210, align: 'left' },
    { key: 'qty',  label: 'Qty (Avg)',           width: 55,  align: 'right' },
    { key: 'unit', label: 'Unit',                width: 45,  align: 'center' },
    { key: 'uc',   label: 'Unit Cost (Mid)',     width: 82,  align: 'right' },
    { key: 'tot',  label: 'Total (Mid)',         width: 100, align: 'right' },
    { key: 'sens', label: 'Sensitivity',         width: 40,  align: 'center' },
  ];

  // Group items by category
  const catOrder = ['Substructure','Shell','Interiors','Services','Equipment',
                    'Special Construction','Sitework','General Conditions','Overhead & Fee','Contingency'];
  const catMap = {};
  for (const it of items) {
    (catMap[it.category] = catMap[it.category] || []).push(it);
  }
  const orderedCats = [
    ...catOrder.filter(c => catMap[c]),
    ...Object.keys(catMap).filter(c => !catOrder.includes(c)),
  ];

  const rows = [];
  for (const cat of orderedCats) {
    rows.push({ _type: 'category', desc: cat, qty: '', unit: '', uc: '', tot: '', sens: '' });
    let catSum = 0;
    for (const it of catMap[cat]) {
      const qty  = (N(it.qty_min) + N(it.qty_max)) / 2;
      const mid  = qty * N(it.unit_cost_mid);
      const scaled = applyMarkups(mid * factor, globals).tot;
      catSum += scaled;
      rows.push({
        desc: short(it.description || it.subcategory || '—', 36),
        qty:  qty % 1 === 0 ? qty.toLocaleString() : qty.toFixed(1),
        unit: it.unit || 'LS',
        uc:   '$' + Math.round(N(it.unit_cost_mid)).toLocaleString(),
        tot:  $c(scaled),
        sens: it.sensitivity ? it.sensitivity[0] : '—',
      });
    }
    rows.push({ _type: 'subtotal',
      desc: cat + ' Subtotal', qty: '', unit: '', uc: '', tot: $c(catSum), sens: '' });
    rows.push({ _type: 'spacer' });
  }

  y = drawTable(doc, ML, y, cols, rows);
}

function buildAssumptions(doc, items, project, globals) {
  let y = sectionTitle(doc, CT, 'Assumptions & Notes');
  y += 8;

  // Global parameters
  doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(9).text('Global Parameters', ML, y);
  y += 14;
  doc.rect(ML, y, CW, 1).fill('#E0E0DA');
  y += 8;

  const params = [
    ['Region Factor',       (N(globals.regionFactor||1)).toFixed(2)],
    ['Escalation',          pct(N(globals.escalation))],
    ['Contingency',         pct(N(globals.contingency))],
    ['General Conditions',  pct(N(globals.generalConditions))],
    ['GC Fee',              pct(N(globals.fee))],
    ['Insurance',           pct(N(globals.insurance))],
    ['Bond',                pct(N(globals.bond))],
    ['Sales Tax',           pct(N(globals.tax))],
    ['Building Area',       N(globals.buildingSF).toLocaleString() + ' SF'],
    ['Labor Type',          project.labor_type || '—'],
  ];

  for (let i = 0; i < params.length; i += 2) {
    const col2x = ML + CW / 2;
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(params[i][0],     ML,      y, { width: 130, lineBreak: false });
    doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(8).text(params[i][1], ML + 130, y, { lineBreak: false });
    if (params[i+1]) {
      doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(params[i+1][0],     col2x,       y, { width: 130, lineBreak: false });
      doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(8).text(params[i+1][1], col2x + 130, y, { lineBreak: false });
    }
    y += 15;
  }

  // Line item notes
  const noted = items.filter(it => it.notes && it.notes.trim());
  if (noted.length) {
    y += 10;
    if (y + 40 > CB) { y = addPage(doc); }
    doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(9).text('Line Item Notes', ML, y);
    y += 14;
    doc.rect(ML, y, CW, 1).fill('#E0E0DA');
    y += 8;

    for (const it of noted) {
      if (y + 24 > CB) { y = addPage(doc); y += 10; }
      doc.fillColor(MUTED).font('Helvetica').fontSize(7.5)
         .text(`${it.category} — ${it.description || it.subcategory || ''}`, ML, y, { lineBreak: false });
      y += 12;
      doc.fillColor(TEXT).font('Helvetica').fontSize(8)
         .text(it.notes, ML + 8, y, { width: CW - 8, lineBreak: true });
      y += (Math.ceil(it.notes.length / 90) * 10) + 6;
    }
  }
}

function buildScopeNotes(doc, estimateNotes) {
  let y = sectionTitle(doc, CT, 'Exclusions, Qualifications & Clarifications');
  y += 4;

  const sections = [
    { type: 'exclusion',     label: 'Exclusions' },
    { type: 'qualification', label: 'Qualifications' },
    { type: 'clarification', label: 'Clarifications' },
  ];

  for (const sec of sections) {
    const items = estimateNotes
      .filter(n => n.type === sec.type)
      .sort((a, b) => a.sort_order - b.sort_order);
    if (!items.length) continue;

    if (y + 30 > CB) { y = addPage(doc); y += 4; }
    doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(9).text(sec.label.toUpperCase(), ML, y);
    y += 12;
    doc.rect(ML, y, CW, 1).fill('#E0E0DA');
    y += 8;

    items.forEach((note, idx) => {
      const text = note.text || '';
      const lineH = 11;
      const estimatedLines = Math.max(1, Math.ceil(text.length / 90));
      const rowH = estimatedLines * lineH + 8;
      if (y + rowH > CB) { y = addPage(doc); }

      doc.fillColor(TEXT).font('Helvetica-Bold').fontSize(8)
         .text(`${idx + 1}.`, ML, y, { width: 16, lineBreak: false });
      doc.fillColor(TEXT).font('Helvetica').fontSize(8)
         .text(text, ML + 18, y, { width: CW - 18, lineBreak: true });
      y += rowH;
    });
    y += 8;
  }
}

function buildAlternates(doc, alternates, alternateItems) {
  let y = sectionTitle(doc, CT, 'Alternates');
  y += 4;

  if (!alternates.length) {
    doc.fillColor(MUTED).font('Helvetica').fontSize(9).text('No alternates defined.', ML, y);
    return;
  }

  // Summary table
  const cols = [
    { key: 'num',    label: '#',           width: 28,  align: 'center' },
    { key: 'title',  label: 'Title',        width: 220, align: 'left' },
    { key: 'type',   label: 'Type',         width: 90,  align: 'left' },
    { key: 'status', label: 'Status',       width: 80,  align: 'left' },
    { key: 'net',    label: 'Net Adj.',     width: 80,  align: 'right' },
    { key: 'total',  label: 'W/ Alternate', width: 34,  align: 'right' },
  ];

  const itemsByAlt = {};
  alternateItems.forEach(ai => {
    if (!itemsByAlt[ai.alternate_id]) itemsByAlt[ai.alternate_id] = [];
    itemsByAlt[ai.alternate_id].push(ai);
  });

  const rows = alternates.map(a => {
    const items = itemsByAlt[a.id] || [];
    const net = items.reduce((s, i) => {
      const t = (Number(i.quantity) || 0) * (Number(i.unit_cost_adjustment) || 0);
      return s + (i.adjustment_type === 'deduct' ? -t : t);
    }, 0);
    return {
      num:    a.number,
      title:  short(a.title, 38),
      type:   a.type === 'deduct' ? 'Deduct' : 'Add',
      status: a.status === 'priced' ? 'Priced' : a.status === 'accepted' ? 'Accepted' : 'Rejected',
      net:    (net >= 0 ? '+' : '') + $c(net),
      total:  '',
      _net:   net,
    };
  });

  y = drawTable(doc, ML, y, cols.slice(0, 5), rows);
  y += 16;

  // Detail per alternate
  for (const a of alternates) {
    const items = itemsByAlt[a.id] || [];
    if (!items.length) continue;

    if (y + 40 > CB) { y = addPage(doc); }

    doc.fillColor(GRAPHITE).font('Helvetica-Bold').fontSize(8.5)
       .text(`Alt #${a.number} — ${short(a.title, 55)}`, ML, y);
    if (a.description) {
      y += 12;
      doc.fillColor(MUTED).font('Helvetica').fontSize(8)
         .text(a.description, ML + 8, y, { width: CW - 8, lineBreak: true });
      y += Math.ceil(a.description.length / 85) * 10 + 2;
    } else {
      y += 12;
    }

    const detailCols = [
      { key: 'desc',   label: 'Description',   width: 260, align: 'left' },
      { key: 'qty',    label: 'Qty',            width: 60,  align: 'right' },
      { key: 'unit',   label: 'Unit Cost Adj.', width: 90,  align: 'right' },
      { key: 'adjt',   label: 'Type',           width: 60,  align: 'center' },
      { key: 'total',  label: 'Total',          width: 62,  align: 'right' },
    ];
    const detailRows = items.map(i => ({
      desc:  short(i.description || '', 44),
      qty:   (Number(i.quantity) || 0).toLocaleString(),
      unit:  $c(Number(i.unit_cost_adjustment) || 0),
      adjt:  i.adjustment_type === 'deduct' ? 'Deduct' : i.adjustment_type === 'replace' ? 'Replace' : 'Add',
      total: (Number(i.total_adjustment) || 0) >= 0 ? `+${$c(Math.abs(i.total_adjustment))}` : $c(i.total_adjustment),
    }));
    y = drawTable(doc, ML, y, detailCols, detailRows, { rowH: 15, hdrH: 17, fs: 7 });
    y += 12;
  }
}

function buildAllowanceSummary(doc, allowanceItems, drawsMap) {
  let y = sectionTitle(doc, CT, 'Allowance Tracking Summary');
  y += 4;

  const cols = [
    { key: 'desc',      label: 'Allowance Item',  width: 210, align: 'left' },
    { key: 'cat',       label: 'Category',         width: 110, align: 'left' },
    { key: 'original',  label: 'Original Budget',  width: 80,  align: 'right' },
    { key: 'drawn',     label: 'Total Drawn',      width: 72,  align: 'right' },
    { key: 'remaining', label: 'Remaining',        width: 60,  align: 'right' },
  ];

  let totalOriginal = 0, totalDrawn = 0;
  const rows = [];

  for (const it of allowanceItems) {
    const original = itemMid(it);
    const itemDraws = drawsMap[it.id] || [];
    const drawn = itemDraws.reduce((s, d) => s + Number(d.amount), 0);
    const remaining = original - drawn;
    totalOriginal += original;
    totalDrawn += drawn;

    rows.push({
      desc:      short(it.description || it.subcategory || '—', 36),
      cat:       short(it.category, 18),
      original:  $c(original),
      drawn:     $c(drawn),
      remaining: $c(remaining),
    });

    // Draw detail rows (indented)
    for (const d of itemDraws) {
      rows.push({
        desc:      `  ${d.drawn_date}  ${short(d.description, 30)}`,
        cat:       '',
        original:  '',
        drawn:     $c(Number(d.amount)),
        remaining: '',
      });
    }
    if (itemDraws.length) rows.push({ _type: 'spacer' });
  }

  rows.push({ _type: 'total',
    desc: 'TOTAL ALLOWANCES',
    cat: '',
    original:  $c(totalOriginal),
    drawn:     $c(totalDrawn),
    remaining: $c(totalOriginal - totalDrawn),
  });

  y = drawTable(doc, ML, y, cols, rows);
}

// ── Main handler ──────────────────────────────────────────────────────────────
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const token = req.headers.authorization?.replace('Bearer ', '');
    if (!token) return res.status(401).json({ error: 'Missing authorization token' });

    if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
      return res.status(500).json({ error: 'Server configuration error: Supabase env vars missing' });
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${token}` } },
    });

    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) return res.status(401).json({ error: 'Unauthorized' });

    const { projectId, scenarioId } = req.body || {};
    if (!projectId || !scenarioId) {
      return res.status(400).json({ error: 'projectId and scenarioId are required' });
    }

    console.log('[export-pdf] Fetching data for project', projectId, 'scenario', scenarioId);

    const [projRes, scenRes, itemsRes] = await Promise.all([
      supabase.from('projects').select('*').eq('id', projectId).single(),
      supabase.from('scenarios').select('*').eq('id', scenarioId).single(),
      supabase.from('line_items').select('*')
        .eq('scenario_id', scenarioId).eq('is_archived', false)
        .order('sort_order', { ascending: true }),
    ]);

    if (projRes.error)  return res.status(404).json({ error: 'Project not found' });
    if (scenRes.error)  return res.status(404).json({ error: 'Scenario not found' });

    const project  = projRes.data;
    const scenario = scenRes.data;
    const items    = itemsRes.data || [];
    const globals  = scenario.globals || {};
    const activeItems = items.filter(it => !it.is_archived && it.in_summary !== false);

    const allowanceItems = activeItems.filter(it => it.is_allowance);
    let drawsMap = {};
    if (allowanceItems.length) {
      const allowanceIds = allowanceItems.map(it => it.id);
      const { data: drawRows } = await supabase
        .from('allowance_draws')
        .select('*')
        .in('line_item_id', allowanceIds)
        .order('drawn_date', { ascending: false });
      if (drawRows) {
        allowanceIds.forEach(id => { drawsMap[id] = []; });
        drawRows.forEach(d => {
          if (drawsMap[d.line_item_id]) drawsMap[d.line_item_id].push(d);
        });
      }
    }

    // Scope notes (estimate_notes table may not exist — handle gracefully)
    let estimateNotes = [];
    try {
      const { data: notesRows } = await supabase
        .from('estimate_notes')
        .select('*')
        .eq('project_id', projectId)
        .eq('scenario_id', scenarioId)
        .order('type')
        .order('sort_order', { ascending: true });
      if (notesRows) estimateNotes = notesRows;
    } catch (_) {}

    // Alternates (table may not exist — handle gracefully)
    let alternates = [], alternateItems = [];
    try {
      const { data: altRows } = await supabase
        .from('alternates')
        .select('*')
        .eq('project_id', projectId)
        .eq('scenario_id', scenarioId)
        .order('number', { ascending: true });
      if (altRows) {
        alternates = altRows;
        if (altRows.length) {
          const altIds = altRows.map(a => a.id);
          const { data: aiRows } = await supabase
            .from('alternate_items')
            .select('*')
            .in('alternate_id', altIds);
          if (aiRows) alternateItems = aiRows;
        }
      }
    } catch (_) {}

    console.log('[export-pdf] Building PDF:', items.length, 'items');

    const totals = computeTotals(activeItems, globals);

    // ── Generate PDF ───────────────────────────────────────────────────────
    _pageNum = 0;
    const doc = new PDFDocument({
      autoFirstPage: false,
      size: 'LETTER',
      margins: { top: 0, left: 0, right: 0, bottom: 0 },
      info: {
        Title: `${project.name} — Cost Estimate`,
        Author: 'CostDeck',
        Subject: 'Construction Cost Estimate',
      },
    });

    const chunks = [];
    doc.on('data', c => chunks.push(c));

    // Page 1: Cover (no chrome — custom design)
    doc.addPage({ size: 'LETTER', margins: { top: 0, left: 0, right: 0, bottom: 0 } });
    _pageNum = 1;
    buildCoverPage(doc, project);

    // Page 2: Executive Summary
    addPage(doc);
    buildExecutiveSummary(doc, project, totals, globals);

    // Page 3: Category Summary
    addPage(doc);
    buildCategorySummary(doc, activeItems, totals, globals);

    // Page 4: Markups Breakdown
    addPage(doc);
    buildMarkupsBreakdown(doc, totals, globals);

    // Page 5: Top 10
    addPage(doc);
    buildTopTen(doc, activeItems, totals, globals);

    // Pages 6+: Detailed line items
    addPage(doc);
    buildDetailedLineItems(doc, activeItems, globals);

    // Last pages: Assumptions
    addPage(doc);
    buildAssumptions(doc, items, project, globals);

    // Allowance summary — only when allowances exist
    if (allowanceItems.length) {
      addPage(doc);
      buildAllowanceSummary(doc, allowanceItems, drawsMap);
    }

    // Scope notes — only when notes exist
    if (estimateNotes.length) {
      addPage(doc);
      buildScopeNotes(doc, estimateNotes);
    }

    // Alternates — only when alternates exist
    if (alternates.length) {
      addPage(doc);
      buildAlternates(doc, alternates, alternateItems);
    }

    doc.end();

    await new Promise(resolve => doc.on('end', resolve));
    const pdfBuffer = Buffer.concat(chunks);

    // Audit log
    await supabase.from('audit_log').insert({
      project_id: projectId,
      user_id: user.id,
      field_name: 'pdf_exported',
      new_value: scenario.name,
      description: `PDF report exported for scenario: ${scenario.name}`,
    });

    const safeName = (project.name || 'Project').replace(/[^a-zA-Z0-9\s]/g, '').trim().replace(/\s+/g, '_');
    const date = new Date().toISOString().slice(0, 10);

    console.log('[export-pdf] Done:', pdfBuffer.length, 'bytes');

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${safeName}_Estimate_${date}.pdf"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.setHeader('Cache-Control', 'no-store');
    return res.end(pdfBuffer);

  } catch (err) {
    Sentry.captureException(err);
    console.error('[export-pdf] Error:', err?.message, err);
    // Only send JSON error if headers not yet sent
    if (!res.headersSent) {
      return res.status(500).json({ error: 'PDF generation failed', detail: err?.message });
    }
  }
}
